apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-goat
  labels:
    app: go-goat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-goat
  template:
    metadata:
      labels:
        app: go-goat
    spec:
      containers:
      - name: go-goat
        image: manuelbcd/go-goat:1.2 # 1.0 #.1.1 #1.2
        ports:
        - containerPort: 8080
